# Generated by Django 2.1 on 2019-03-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
