# Generated by Django 2.1.1 on 2019-03-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0003_userstock_userstockstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userstockstransaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
